version: '3'
services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile
            args:
              - API_MODULE_VERSION=${MODULE_VER}
              - API_MODULE_REPO_URL=${MODULE_REPO}
        restart: always
        ports:
            - "${WEB_PORT}:80"
    db:
        image: postgres:12.3
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./data/initdb/:/docker-entrypoint-initdb.d